name := "functional-structures-refactoring-kata"
version := "1.0"
scalaVersion := "2.12.2"
libraryDependencies += "org.typelevel" %% "cats" % "0.9.0"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.1" % "test"
